compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.0.2.cjs

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - ia32
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32
